version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
      - 6370:6370
    expose:
      - 6370
    command: redis-server /etc/redis/redis.conf --port 6370 
    volumes:
      - ./config/redis.conf:/etc/redis/redis.conf
